from typing import Protocol, Dict, Any

class JiraClient(Protocol):
    async def search_issues(self, jql: str, max_results: int = 50) -> Dict[str, Any]: ...
    async def get_issue_changelog(self, issue_key: str) -> Dict[str, Any]: ...
    async def me(self) -> Dict[str, Any]: ...
